name: Build
on: push
jobs:
  apk:
    name: APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build APK
        run: |
          ./gradlew assembleDebug
      - name: Archive APK
        uses: actions/upload-artifact@v3
        with:
          name: storage-info-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
